### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by muzuitech** [jr00ck/gravity-forms-update-credit-card-for-stripe#2]
I tried to use this code. It seems to be useful but its not working for me. 

Here is the problem

$customer =  \Stripe\Customer::retrieve($customer_id);
			$customer->card = 'pm_1GJiXTDJ85qMQLfCayqM82GX'; //$response->id;
			$save = $customer->save();

But it always says no such token found. I used validation filter as you used and trying to upgrade the card as well. 

Can you tell me what is the issue with this?

**Comment by jr00ck** [comment]
This code is very outdated and has been abandoned by me years ago. I use a service called Churn Buster to handle updating credit cards.
